### ISSUE TITLE
Bug on the latest version 1.1.6-alpha.3

### ISSUE THREAD

**Issue by tegaologe** [lbgm/pro-calendar-vue#19]
I am facing two issues with my Quasar Vue.js project:

Compatibility Issue:
I am unable to make it work with version 1.1.6-alpha.3 of a certain package. When attempting to use this latest version, I encounter the error message: vue__WEBPACK_IMPORTED_MODULE_0__.hasInjectionContext) is not a function. It appears that there might be some compatibility problems between Vue.js and its dependencies.

Incorrect Date Display:
Moreover, when reverting to the older version, I encounter issues with date display. If a date is supposed to be shown as the 26th of the month, it ends up displaying as the 27th of July instead.

To address these concerns, I would highly appreciate any assistance you can provide. I have attached a screenshot for your reference.

Thank you again for your help!

<img width="776" alt="Screenshot 2023-07-26 at 6 34 54 PM" src="https://github.com/lbgm/pro-calendar-vue/assets/101271396/cdb4be33-f142-4817-a01f-4f02d92803a8">
<img width="730" alt="Screenshot 2023-07-26 at 6 30 43 PM" src="https://github.com/lbgm/pro-calendar-vue/assets/101271396/b7f032cb-918c-46e9-abbd-667d139c8e80">

**Comment by lbgm** [comment]
hello @tegaologe .

**Comment by lbgm** [comment]
did you init your quasar project with `vite` ?

**Comment by tegaologe** [comment]
I did it with webpack not vite

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by lbgm** [comment]
maybe the problem. the lib is based on vite.
